import { Point } from 'paper';

import { bounds } from '../../constants';

/**
 * Perform a translation operation. The translation has to be done on both the
 * item itself and the item that displays the manipulation handlers.
 *
 * @param {Object} selectedItem Object with selected item in drawings and map canvases.
 * @param {Object} originBound Bound used as origin for dragging action.
 * @param {Object} delta Current delta generated by dragging the user cursor.
 */
export default function resize({ drawings, map }, originBound, delta) {
  if (!drawings || !map) {
    return undefined;
  }

  let originPoint;
  // Determine delta depending on the drag origin and the current point
  switch (originBound) {
    case bounds.bottomRight:
      originPoint = drawings.bounds.topLeft;
      break;

    case bounds.bottomLeft:
      originPoint = drawings.bounds.topRight;
      delta.set({ x : -1 * delta.x, y : delta.y });
      break;

    default:
      break;
  }

  // Calculate scaling factor based on the given delta
  const scalingFactor = {
    x : (drawings.bounds.width + delta.x) / drawings.bounds.width,
    y : (drawings.bounds.height + delta.y) / drawings.bounds.height,
  };

  // Scale the selected item in the drawings canvas
  drawings.scale(
    new Point(scalingFactor.x, scalingFactor.y),
    originPoint,
  );

  // Scale the selected item in the map
  map.scale(
    new Point(scalingFactor.x, scalingFactor.y),
    originPoint,
  );

  return { scalingFactor, originPoint };
}
